### ISSUE TITLE
Firewalld error when running the ansible-playbook

### ISSUE THREAD

**Issue by pnovok** [couchbaselabs/ansible-couchbase-server#11]
Trying to install the cluster using the following config from the examples dir: 

ansible-playbook --private-key ~/.ssh/pn-key-pair.pem -i full_hosts full.yml and getting the following error. 

Should firewalld be installed on each node? Right now I don't have it.

ERROR! couldn't resolve module/action 'ansible.posix.firewalld'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/roles/couchbaselabs.couchbase_server/tasks/os/firewalld.yml': line 36, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# 4369: epmd - Erlang Port Mapper Daemon (Node-to-Node)
- name: Add port 4369
  ^ here

**Comment by pierreyvesv** [comment]
Hello,
double check that you have installed the posix collection
`ansible-galaxy collection install ansible.posix` will install it in ~/.ansible/collections
